# dubelyoo.com

title: dubelyoo
description: Welcome to my site of a technology mishmash (and other hobbies) notes/articles for reference. It's really just for me.
show_downloads: false

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
