# dubelyoo.com

title: dubelyoo
description: A tech (and other hobbies) mishmash of notes/articles. It's really just for me.

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
